
name: "Hello world app"
    
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: install depenencies
        run: pip3 install -r requirements.txt
      - name: run tests
        run: python3 -m pytest test.py
      - name: deploy
        run: python3 -m app.py
